version: 2
jobs:
  one:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting job one
          command: echo running first job
          
      - run:
          name: Print the Current Time
          command: date
          command: sleep 10
          
          
  two:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting job two
          command: echo running second job

      - run:
          name: Print the Current Time
          command: date
          command: sleep 10
          
workflows:
   version: 2
   one_and_two:
     jobs:
       - one
       - two
